-- CREATE USER ADMINUSER
CREATE USER adminalto WITH PASSWORD 'tobiytaison12';

-- CREATE DB TIENDA
CREATE DATABASE alto_db WITH ENCODING 'UTF8' TEMPLATE template0 OWNER adminalto;

-- GRANT ROLES TO USER ADMINUSER
GRANT ALL PRIVILEGES ON DATABASE alto_db TO adminalto;

